#include <Windows.h>
#include <string>
#include <memory>

// Умный указатель для автоматического освобождения библиотеки
struct HandleDeleter {
    void operator()(HMODULE module) const {
        if (module) FreeLibrary(module);
    }
};
using ScopedModule = std::unique_ptr<std::remove_pointer<HMODULE>::type, HandleDeleter>;

ScopedModule hOriginalDll;
FARPROC g_OriginalFunctions[259] = { nullptr };

// Имена экспортов в том же порядке, что и в .def файле
const char* g_FunctionNames[] = {
    "SymEnumSourceLinesEx",
    "SymEnumSourceLinesExW",
    "SymGetLineFromAddrExW64",
    "SymGetLineFromNameExW64",
    "SymGetLineNextExW64",
    "SymGetLinePrevExW64",
    "SymGetLineFromAddrEx64",
    "SymGetLineFromNameEx64",
    "SymGetLineNextEx64",
    "SymGetLinePrevEx64",
    "SymGetLineFromAddrEx",
    "SymGetLineFromNameEx",
    "SymGetLineNextEx",
    "SymGetLinePrevEx",
    "SymGetLineFromInlineContextEx",
    "SymGetLineFromInlineContextExW",
    "SymEnumSourceFilesEx",
    "SymEnumSourceFilesExW",
    "SymFindNextMatchingInlineFrame",
    "SymAllocDiaString",
    "SymFreeDiaString",
    "SymGetDiaSession",
    "SymGetOmapBlockBase",
    "SymSetDiaSession",
    "_EFN_DumpImage",
    "DbgHelpCreateUserDump",
    "DbgHelpCreateUserDumpW",
    "EnumDirTree",
    "EnumDirTreeW",
    "EnumerateLoadedModules64",
    "EnumerateLoadedModules",
    "EnumerateLoadedModulesEx",
    "EnumerateLoadedModulesExW",
    "EnumerateLoadedModulesW64",
    "ExtensionApiVersion",
    "FindDebugInfoFile",
    "FindDebugInfoFileEx",
    "FindDebugInfoFileExW",
    "FindExecutableImage",
    "FindExecutableImageEx",
    "FindExecutableImageExW",
    "FindFileInPath",
    "FindFileInSearchPath",
    "GetSymLoadError",
    "GetTimestampForLoadedLibrary",
    "ImageDirectoryEntryToData",
    "ImageDirectoryEntryToDataEx",
    "ImageNtHeader",
    "ImageRvaToSection",
    "ImageRvaToVa",
    "ImagehlpApiVersion",
    "ImagehlpApiVersionEx",
    "MakeSureDirectoryPathExists",
    "MapDebugInformation",
    "MiniDumpReadDumpStream",
    "MiniDumpWriteDump",
    "RangeMapAddPeImageSections",
    "RangeMapCreate",
    "RangeMapFree",
    "RangeMapRead",
    "RangeMapRemove",
    "RangeMapWrite",
    "RemoveInvalidModuleList",
    "ReportSymbolLoadSummary",
    "SearchTreeForFile",
    "SearchTreeForFileW",
    "SetCheckUserInterruptShared",
    "SetSymLoadError",
    "StackWalk64",
    "StackWalk",
    "StackWalkEx",
    "SymAddSourceStream",
    "SymAddSourceStreamA",
    "SymAddSourceStreamW",
    "SymAddSymbol",
    "SymAddSymbolW",
    "SymAddrIncludeInlineTrace",
    "SymCleanup",
    "SymCompareInlineTrace",
    "SymDeleteSymbol",
    "SymDeleteSymbolW",
    "SymEnumLines",
    "SymEnumLinesW",
    "SymEnumProcesses",
    "SymEnumSourceFileTokens",
    "SymEnumSourceFiles",
    "SymEnumSourceFilesW",
    "SymEnumSourceLines",
    "SymEnumSourceLinesW",
    "SymEnumSym",
    "SymEnumSymbols",
    "SymEnumSymbolsEx",
    "SymEnumSymbolsExW",
    "SymEnumSymbolsForAddr",
    "SymEnumSymbolsForAddrW",
    "SymEnumSymbolsW",
    "SymEnumTypes",
    "SymEnumTypesByName",
    "SymEnumTypesByNameW",
    "SymEnumTypesW",
    "SymEnumerateModules64",
    "SymEnumerateModules",
    "SymEnumerateModulesW64",
    "SymEnumerateSymbols64",
    "SymEnumerateSymbols",
    "SymEnumerateSymbolsW64",
    "SymEnumerateSymbolsW",
    "SymFindDebugInfoFile",
    "SymFindDebugInfoFileW",
    "SymFindExecutableImage",
    "SymFindExecutableImageW",
    "SymFindFileInPath",
    "SymFindFileInPathW",
    "SymFromAddr",
    "SymFromAddrW",
    "SymFromIndex",
    "SymFromIndexW",
    "SymFromInlineContext",
    "SymFromInlineContextW",
    "SymFromName",
    "SymFromNameW",
    "SymFromToken",
    "SymFromTokenW",
    "SymFunctionTableAccess64",
    "SymFunctionTableAccess64AccessRoutines",
    "SymFunctionTableAccess",
    "SymGetExtendedOption",
    "SymGetFileLineOffsets64",
    "SymGetHomeDirectory",
    "SymGetHomeDirectoryW",
    "SymGetLineFromAddr64",
    "SymGetLineFromAddr",
    "SymGetLineFromAddrW64",
    "SymGetLineFromInlineContext",
    "SymGetLineFromInlineContextW",
    "SymGetLineFromName64",
    "SymGetLineFromName",
    "SymGetLineFromNameW64",
    "SymGetLineNext64",
    "SymGetLineNext",
    "SymGetLineNextW64",
    "SymGetLinePrev64",
    "SymGetLinePrev",
    "SymGetLinePrevW64",
    "SymGetModuleBase64",
    "SymGetModuleBase",
    "SymGetModuleInfo64",
    "SymGetModuleInfo",
    "SymGetModuleInfoW64",
    "SymGetModuleInfoW",
    "SymGetOmaps",
    "SymGetOptions",
    "SymGetScope",
    "SymGetScopeW",
    "SymGetSearchPath",
    "SymGetSearchPathW",
    "SymGetSourceFile",
    "SymGetSourceFileChecksum",
    "SymGetSourceFileChecksumW",
    "SymGetSourceFileFromToken",
    "SymGetSourceFileFromTokenW",
    "SymGetSourceFileToken",
    "SymGetSourceFileTokenW",
    "SymGetSourceFileW",
    "SymGetSourceVarFromToken",
    "SymGetSourceVarFromTokenW",
    "SymGetSymFromAddr64",
    "SymGetSymFromAddr",
    "SymGetSymFromName64",
    "SymGetSymFromName",
    "SymGetSymNext64",
    "SymGetSymNext",
    "SymGetSymPrev64",
    "SymGetSymPrev",
    "SymGetSymbolFile",
    "SymGetSymbolFileW",
    "SymGetTypeFromName",
    "SymGetTypeFromNameW",
    "SymGetTypeInfo",
    "SymGetTypeInfoEx",
    "SymGetUnwindInfo",
    "SymInitialize",
    "SymInitializeW",
    "SymLoadModule64",
    "SymLoadModule",
    "SymLoadModuleEx",
    "SymLoadModuleExW",
    "SymMatchFileName",
    "SymMatchFileNameW",
    "SymMatchString",
    "SymMatchStringA",
    "SymMatchStringW",
    "SymNext",
    "SymNextW",
    "SymPrev",
    "SymPrevW",
    "SymQueryInlineTrace",
    "SymRefreshModuleList",
    "SymRegisterCallback64",
    "SymRegisterCallback",
    "SymRegisterCallbackW64",
    "SymRegisterFunctionEntryCallback64",
    "SymRegisterFunctionEntryCallback",
    "SymSearch",
    "SymSearchW",
    "SymSetContext",
    "SymSetExtendedOption",
    "SymSetHomeDirectory",
    "SymSetHomeDirectoryW",
    "SymSetOptions",
    "SymSetParentWindow",
    "SymSetScopeFromAddr",
    "SymSetScopeFromIndex",
    "SymSetScopeFromInlineContext",
    "SymSetSearchPath",
    "SymSetSearchPathW",
    "SymSrvDeltaName",
    "SymSrvDeltaNameW",
    "SymSrvGetFileIndexInfo",
    "SymSrvGetFileIndexInfoW",
    "SymSrvGetFileIndexString",
    "SymSrvGetFileIndexStringW",
    "SymSrvGetFileIndexes",
    "SymSrvGetFileIndexesW",
    "SymSrvGetSupplement",
    "SymSrvGetSupplementW",
    "SymSrvIsStore",
    "SymSrvIsStoreW",
    "SymSrvStoreFile",
    "SymSrvStoreFileW",
    "SymSrvStoreSupplement",
    "SymSrvStoreSupplementW",
    "SymUnDName64",
    "SymUnDName",
    "SymUnloadModule64",
    "SymUnloadModule",
    "UnDecorateSymbolName",
    "UnDecorateSymbolNameW",
    "UnmapDebugInformation",
    "WinDbgExtensionDllInit",
    "block",
    "chksym",
    "dbghelp",
    "dh",
    "fptr",
    "homedir",
    "inlinedbg",
    "itoldyouso",
    "lmi",
    "lminfo",
    "omap",
    "optdbgdump",
    "optdbgdumpaddr",
    "srcfiles",
    "stack_force_ebp",
    "stackdbg",
    "sym",
    "symsrv",
    "vc7fpo"
};

bool LoadOriginalLibrary() {
    char sysPath[MAX_PATH] = { 0 };

    // Получаем путь к SysWOW64 (для 64-битной Windows)
    if (GetSystemWow64DirectoryA(sysPath, MAX_PATH) == 0) {
        // На 32-битной системе используем System32
        strcpy_s(sysPath, "C:\\Windows\\System32"); //Поменять, потому что может быть и не диск C
    }

    std::string fullPath = sysPath;
    fullPath += "\\dbghelp.dll";

    HMODULE hTemp = LoadLibraryA(fullPath.c_str());
    if (!hTemp)
        return false;

    hOriginalDll.reset(hTemp);

    // Загружаем адреса по именам
    for (size_t i = 0; i < 259; ++i) {
        g_OriginalFunctions[i] = GetProcAddress(hTemp, (LPCSTR)(g_FunctionNames[i]));
        if (!g_OriginalFunctions[i]) {
            // Не критично, если какая-то функция не найдена, но для надёжности можно вернуть false
            // return false;
        }
    }
    return true;
}

void UnloadOriginalLibrary() {
    hOriginalDll.reset();
}

// Генератор прокси‑функций
#define GENERATE_PROXY_FUNCTION(idx) \
extern "C" __declspec(naked) void __stdcall ProxyFunction##idx() { \
    __asm { jmp [g_OriginalFunctions + idx * 4] } \
}

// Создаём 259 функций
GENERATE_PROXY_FUNCTION(0)
GENERATE_PROXY_FUNCTION(1)
GENERATE_PROXY_FUNCTION(2)
GENERATE_PROXY_FUNCTION(3)
GENERATE_PROXY_FUNCTION(4)
GENERATE_PROXY_FUNCTION(5)
GENERATE_PROXY_FUNCTION(6)
GENERATE_PROXY_FUNCTION(7)
GENERATE_PROXY_FUNCTION(8)
GENERATE_PROXY_FUNCTION(9)
GENERATE_PROXY_FUNCTION(10)
GENERATE_PROXY_FUNCTION(11)
GENERATE_PROXY_FUNCTION(12)
GENERATE_PROXY_FUNCTION(13)
GENERATE_PROXY_FUNCTION(14)
GENERATE_PROXY_FUNCTION(15)
GENERATE_PROXY_FUNCTION(16)
GENERATE_PROXY_FUNCTION(17)
GENERATE_PROXY_FUNCTION(18)
GENERATE_PROXY_FUNCTION(19)
GENERATE_PROXY_FUNCTION(20)
GENERATE_PROXY_FUNCTION(21)
GENERATE_PROXY_FUNCTION(22)
GENERATE_PROXY_FUNCTION(23)
GENERATE_PROXY_FUNCTION(24)
GENERATE_PROXY_FUNCTION(25)
GENERATE_PROXY_FUNCTION(26)
GENERATE_PROXY_FUNCTION(27)
GENERATE_PROXY_FUNCTION(28)
GENERATE_PROXY_FUNCTION(29)
GENERATE_PROXY_FUNCTION(30)
GENERATE_PROXY_FUNCTION(31)
GENERATE_PROXY_FUNCTION(32)
GENERATE_PROXY_FUNCTION(33)
GENERATE_PROXY_FUNCTION(34)
GENERATE_PROXY_FUNCTION(35)
GENERATE_PROXY_FUNCTION(36)
GENERATE_PROXY_FUNCTION(37)
GENERATE_PROXY_FUNCTION(38)
GENERATE_PROXY_FUNCTION(39)
GENERATE_PROXY_FUNCTION(40)
GENERATE_PROXY_FUNCTION(41)
GENERATE_PROXY_FUNCTION(42)
GENERATE_PROXY_FUNCTION(43)
GENERATE_PROXY_FUNCTION(44)
GENERATE_PROXY_FUNCTION(45)
GENERATE_PROXY_FUNCTION(46)
GENERATE_PROXY_FUNCTION(47)
GENERATE_PROXY_FUNCTION(48)
GENERATE_PROXY_FUNCTION(49)
GENERATE_PROXY_FUNCTION(50)
GENERATE_PROXY_FUNCTION(51)
GENERATE_PROXY_FUNCTION(52)
GENERATE_PROXY_FUNCTION(53)
GENERATE_PROXY_FUNCTION(54)
GENERATE_PROXY_FUNCTION(55)
GENERATE_PROXY_FUNCTION(56)
GENERATE_PROXY_FUNCTION(57)
GENERATE_PROXY_FUNCTION(58)
GENERATE_PROXY_FUNCTION(59)
GENERATE_PROXY_FUNCTION(60)
GENERATE_PROXY_FUNCTION(61)
GENERATE_PROXY_FUNCTION(62)
GENERATE_PROXY_FUNCTION(63)
GENERATE_PROXY_FUNCTION(64)
GENERATE_PROXY_FUNCTION(65)
GENERATE_PROXY_FUNCTION(66)
GENERATE_PROXY_FUNCTION(67)
GENERATE_PROXY_FUNCTION(68)
GENERATE_PROXY_FUNCTION(69)
GENERATE_PROXY_FUNCTION(70)
GENERATE_PROXY_FUNCTION(71)
GENERATE_PROXY_FUNCTION(72)
GENERATE_PROXY_FUNCTION(73)
GENERATE_PROXY_FUNCTION(74)
GENERATE_PROXY_FUNCTION(75)
GENERATE_PROXY_FUNCTION(76)
GENERATE_PROXY_FUNCTION(77)
GENERATE_PROXY_FUNCTION(78)
GENERATE_PROXY_FUNCTION(79)
GENERATE_PROXY_FUNCTION(80)
GENERATE_PROXY_FUNCTION(81)
GENERATE_PROXY_FUNCTION(82)
GENERATE_PROXY_FUNCTION(83)
GENERATE_PROXY_FUNCTION(84)
GENERATE_PROXY_FUNCTION(85)
GENERATE_PROXY_FUNCTION(86)
GENERATE_PROXY_FUNCTION(87)
GENERATE_PROXY_FUNCTION(88)
GENERATE_PROXY_FUNCTION(89)
GENERATE_PROXY_FUNCTION(90)
GENERATE_PROXY_FUNCTION(91)
GENERATE_PROXY_FUNCTION(92)
GENERATE_PROXY_FUNCTION(93)
GENERATE_PROXY_FUNCTION(94)
GENERATE_PROXY_FUNCTION(95)
GENERATE_PROXY_FUNCTION(96)
GENERATE_PROXY_FUNCTION(97)
GENERATE_PROXY_FUNCTION(98)
GENERATE_PROXY_FUNCTION(99)
GENERATE_PROXY_FUNCTION(100)
GENERATE_PROXY_FUNCTION(101)
GENERATE_PROXY_FUNCTION(102)
GENERATE_PROXY_FUNCTION(103)
GENERATE_PROXY_FUNCTION(104)
GENERATE_PROXY_FUNCTION(105)
GENERATE_PROXY_FUNCTION(106)
GENERATE_PROXY_FUNCTION(107)
GENERATE_PROXY_FUNCTION(108)
GENERATE_PROXY_FUNCTION(109)
GENERATE_PROXY_FUNCTION(110)
GENERATE_PROXY_FUNCTION(111)
GENERATE_PROXY_FUNCTION(112)
GENERATE_PROXY_FUNCTION(113)
GENERATE_PROXY_FUNCTION(114)
GENERATE_PROXY_FUNCTION(115)
GENERATE_PROXY_FUNCTION(116)
GENERATE_PROXY_FUNCTION(117)
GENERATE_PROXY_FUNCTION(118)
GENERATE_PROXY_FUNCTION(119)
GENERATE_PROXY_FUNCTION(120)
GENERATE_PROXY_FUNCTION(121)
GENERATE_PROXY_FUNCTION(122)
GENERATE_PROXY_FUNCTION(123)
GENERATE_PROXY_FUNCTION(124)
GENERATE_PROXY_FUNCTION(125)
GENERATE_PROXY_FUNCTION(126)
GENERATE_PROXY_FUNCTION(127)
GENERATE_PROXY_FUNCTION(128)
GENERATE_PROXY_FUNCTION(129)
GENERATE_PROXY_FUNCTION(130)
GENERATE_PROXY_FUNCTION(131)
GENERATE_PROXY_FUNCTION(132)
GENERATE_PROXY_FUNCTION(133)
GENERATE_PROXY_FUNCTION(134)
GENERATE_PROXY_FUNCTION(135)
GENERATE_PROXY_FUNCTION(136)
GENERATE_PROXY_FUNCTION(137)
GENERATE_PROXY_FUNCTION(138)
GENERATE_PROXY_FUNCTION(139)
GENERATE_PROXY_FUNCTION(140)
GENERATE_PROXY_FUNCTION(141)
GENERATE_PROXY_FUNCTION(142)
GENERATE_PROXY_FUNCTION(143)
GENERATE_PROXY_FUNCTION(144)
GENERATE_PROXY_FUNCTION(145)
GENERATE_PROXY_FUNCTION(146)
GENERATE_PROXY_FUNCTION(147)
GENERATE_PROXY_FUNCTION(148)
GENERATE_PROXY_FUNCTION(149)
GENERATE_PROXY_FUNCTION(150)
GENERATE_PROXY_FUNCTION(151)
GENERATE_PROXY_FUNCTION(152)
GENERATE_PROXY_FUNCTION(153)
GENERATE_PROXY_FUNCTION(154)
GENERATE_PROXY_FUNCTION(155)
GENERATE_PROXY_FUNCTION(156)
GENERATE_PROXY_FUNCTION(157)
GENERATE_PROXY_FUNCTION(158)
GENERATE_PROXY_FUNCTION(159)
GENERATE_PROXY_FUNCTION(160)
GENERATE_PROXY_FUNCTION(161)
GENERATE_PROXY_FUNCTION(162)
GENERATE_PROXY_FUNCTION(163)
GENERATE_PROXY_FUNCTION(164)
GENERATE_PROXY_FUNCTION(165)
GENERATE_PROXY_FUNCTION(166)
GENERATE_PROXY_FUNCTION(167)
GENERATE_PROXY_FUNCTION(168)
GENERATE_PROXY_FUNCTION(169)
GENERATE_PROXY_FUNCTION(170)
GENERATE_PROXY_FUNCTION(171)
GENERATE_PROXY_FUNCTION(172)
GENERATE_PROXY_FUNCTION(173)
GENERATE_PROXY_FUNCTION(174)
GENERATE_PROXY_FUNCTION(175)
GENERATE_PROXY_FUNCTION(176)
GENERATE_PROXY_FUNCTION(177)
GENERATE_PROXY_FUNCTION(178)
GENERATE_PROXY_FUNCTION(179)
GENERATE_PROXY_FUNCTION(180)
GENERATE_PROXY_FUNCTION(181)
GENERATE_PROXY_FUNCTION(182)
GENERATE_PROXY_FUNCTION(183)
GENERATE_PROXY_FUNCTION(184)
GENERATE_PROXY_FUNCTION(185)
GENERATE_PROXY_FUNCTION(186)
GENERATE_PROXY_FUNCTION(187)
GENERATE_PROXY_FUNCTION(188)
GENERATE_PROXY_FUNCTION(189)
GENERATE_PROXY_FUNCTION(190)
GENERATE_PROXY_FUNCTION(191)
GENERATE_PROXY_FUNCTION(192)
GENERATE_PROXY_FUNCTION(193)
GENERATE_PROXY_FUNCTION(194)
GENERATE_PROXY_FUNCTION(195)
GENERATE_PROXY_FUNCTION(196)
GENERATE_PROXY_FUNCTION(197)
GENERATE_PROXY_FUNCTION(198)
GENERATE_PROXY_FUNCTION(199)
GENERATE_PROXY_FUNCTION(200)
GENERATE_PROXY_FUNCTION(201)
GENERATE_PROXY_FUNCTION(202)
GENERATE_PROXY_FUNCTION(203)
GENERATE_PROXY_FUNCTION(204)
GENERATE_PROXY_FUNCTION(205)
GENERATE_PROXY_FUNCTION(206)
GENERATE_PROXY_FUNCTION(207)
GENERATE_PROXY_FUNCTION(208)
GENERATE_PROXY_FUNCTION(209)
GENERATE_PROXY_FUNCTION(210)
GENERATE_PROXY_FUNCTION(211)
GENERATE_PROXY_FUNCTION(212)
GENERATE_PROXY_FUNCTION(213)
GENERATE_PROXY_FUNCTION(214)
GENERATE_PROXY_FUNCTION(215)
GENERATE_PROXY_FUNCTION(216)
GENERATE_PROXY_FUNCTION(217)
GENERATE_PROXY_FUNCTION(218)
GENERATE_PROXY_FUNCTION(219)
GENERATE_PROXY_FUNCTION(220)
GENERATE_PROXY_FUNCTION(221)
GENERATE_PROXY_FUNCTION(222)
GENERATE_PROXY_FUNCTION(223)
GENERATE_PROXY_FUNCTION(224)
GENERATE_PROXY_FUNCTION(225)
GENERATE_PROXY_FUNCTION(226)
GENERATE_PROXY_FUNCTION(227)
GENERATE_PROXY_FUNCTION(228)
GENERATE_PROXY_FUNCTION(229)
GENERATE_PROXY_FUNCTION(230)
GENERATE_PROXY_FUNCTION(231)
GENERATE_PROXY_FUNCTION(232)
GENERATE_PROXY_FUNCTION(233)
GENERATE_PROXY_FUNCTION(234)
GENERATE_PROXY_FUNCTION(235)
GENERATE_PROXY_FUNCTION(236)
GENERATE_PROXY_FUNCTION(237)
GENERATE_PROXY_FUNCTION(238)
GENERATE_PROXY_FUNCTION(239)
GENERATE_PROXY_FUNCTION(240)
GENERATE_PROXY_FUNCTION(241)
GENERATE_PROXY_FUNCTION(242)
GENERATE_PROXY_FUNCTION(243)
GENERATE_PROXY_FUNCTION(244)
GENERATE_PROXY_FUNCTION(245)
GENERATE_PROXY_FUNCTION(246)
GENERATE_PROXY_FUNCTION(247)
GENERATE_PROXY_FUNCTION(248)
GENERATE_PROXY_FUNCTION(249)
GENERATE_PROXY_FUNCTION(250)
GENERATE_PROXY_FUNCTION(251)
GENERATE_PROXY_FUNCTION(252)
GENERATE_PROXY_FUNCTION(253)
GENERATE_PROXY_FUNCTION(254)
GENERATE_PROXY_FUNCTION(255)
GENERATE_PROXY_FUNCTION(256)
GENERATE_PROXY_FUNCTION(257)
GENERATE_PROXY_FUNCTION(258)